language: python

python:
  - "3.6"
  - "3.6-dev"

script:
  - pip install -r requirements/prod.txt
  - pip install -r requirements/dev.txt
  - flake8 gol
  - PYTHONPATH=$PYTHONPATH:. pytest --cov=gol tests
  - coverage report -m
